AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an S3 bucket'

Resources:
  SpaceLiftBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spacelift-gkirwan-bucket-cft
      Tags:
        - Key: Name
          Value: spacelift_gkirwan_bucket
        - Key: Environment
          Value: Dev